### ISSUE TITLE
Documenting your intentions

### ISSUE THREAD

**Issue by adrianblynch** [ant300zx/tfl_underground#1]
What are your intentions for this project? You didn't use a library or framework? Why is that?

**Comment by arc76** [comment]
My intentions for this project was to improve my knowledge of writing plain JavaScript without any libraries. Once I get to a point where I am happy with my understanding, I will then look to use libraries but have yet to decide which one.

**Comment by adrianblynch** [comment]
Cool! That should be in your readme...

**Comment by arc76** [comment]
Thanks. I've just updated it.
